### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by jrunning**
This PR fleshes out `README.md`. The content mostly comes from
<https://theantlrguy.atlassian.net/wiki/display/ANTLR4/JavaScript+Target>, with very minor changes apart from formatting. I've also included instructions on installing from NPM under the assumption that #26 will be merged.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hi,
I've added a direct link to the wiki page, I'm not sure I can maintain 2 web pages :-)

**Comment by jrunning** [comment]
How can I contribute to the wiki documentation? It's very difficult to use at present, and the Node.js instructions need to be updated.

**Comment by ericvergnaud** [comment]
You need to request authorization from Terence.

**Comment by jrunning** [comment]
Okay, wouldn't it be better to have the documentation somewhere that people who want to help improve it don't have to request authorization from Terence? It seems like that could get tiresome for Terence.

**Comment by ericvergnaud** [comment]
Well with GitHub, you'd have to bother someone every time you commit since the PRs would have to be approved.
Also, it's one product, with multiple runtimes, so we'd like to keep the docs in one place.
I believe Terence is fine with being bothered once for good reasons.

**Comment by jrunning** [comment]
That's really nice of Terence, but I don't think you're going to get a lot of takers. If a developer sees a broken link in a README on GitHub, where they already have an account, they can make a PR to fix it in less than a minute. If they see a broken link on your closed wiki, even if they know how to contact Terence, they're not going to take the time to do so, and then wait for a response, and create an account, and figure out how to use Confluence. 

I realize I'm not going to convince you, so I'll stop beating a dead horse, but I think one of the keys to attracting good contributors is removing as many barriers as possible and letting them use the tools with which they're already proficient (which, in the case of JavaScript developers, means GitHub). For people who just want to contribute a small patch here and there, “You have to get authorization from Terence and use this other tool” is a large enough barrier than many—most, if you ask me—just won't bother.

**Comment by parrt** [comment]
I was in fact tempted to move stuff to github but there was a huge amount of documentation that used a lot of  special formatting that was going to give markdown trouble. This site also manages documentation for multiple tools. I can’t turn on the self registration because spammers took over. almost nobody signed up to help edit anyway. ;)

 I would agree that more people would change things if it were part of github…  definitely something to think about in the future.

 you should have received a username and email from the site now.

Ter

**Pull request closed without merging**
